# Generated by Django 5.2.4 on 2025-07-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iron", "0002_remove_workoutsessionexercise_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsessionexercise",
            name="workout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_exercises",
                to="iron.workoutsession",
            ),
        ),
    ]
