# Generated by Django 5.2.4 on 2025-07-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iron", "0003_alter_workoutsessionexercise_workout_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutsessionexerciseset",
            options={"ordering": ["-created_at"]},
        ),
    ]
